In [2]:
import pandas as pd

In [7]:
df = pd.read_csv(
    r"C:\Users\Admin\Documents\GitHub\Data_Science\TASKS\MY_WORKS\syx.txt",
    sep=r"\s+"
)

df.head()

Empty DataFrame
Columns: [this, is, my, file]
Index: []

In [11]:
df = pd.read_csv(
    r"https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2025-financial-year-provisional/Download-data/annual-enterprise-survey-2025-financial-year-provisional-size-bands.csv"
)

df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.columns
df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.dtypes

year                      int64
industry_code_ANZSIC        str
industry_name_ANZSIC        str
rme_size_grp                str
variable                    str
value                       str
unit                        str
Unnamed: 7              float64
Unnamed: 8              float64
Unnamed: 9              float64
Unnamed: 10                 str
Unnamed: 11                 str
Unnamed: 12                 str
Unnamed: 13                 str
Unnamed: 14                 str
Unnamed: 15                 str
dtype: object

In [18]:
df.describe()

               year  Unnamed: 7  Unnamed: 8   Unnamed: 9
count  23220.000000         0.0         0.0    41.000000
mean    2018.000000         NaN         NaN  2022.268293
std        4.320587         NaN         NaN     0.448575
min     2011.000000         NaN         NaN  2022.000000
25%     2014.000000         NaN         NaN  2022.000000
50%     2018.000000         NaN         NaN  2022.000000
75%     2022.000000         NaN         NaN  2023.000000
max     2025.000000         NaN         NaN  2023.000000

In [25]:
df.dtypes[df.dtypes =="int"].index

Index(['year'], dtype='str')

In [30]:
df[df.dtypes[df.dtypes =="int"].index].describe()

               year
count  23220.000000
mean    2018.000000
std        4.320587
min     2011.000000
25%     2014.000000
50%     2018.000000
75%     2022.000000
max     2025.000000

In [33]:
df["value"][2:10]

2      279
3     8187
4     8866
5     7618
6      770
7    55700
8    32155
9    21777
Name: value, dtype: str