In [44]:
import pandas as pd
import numpy as np

data = {
    "Name": [
        "Rahul", "Amit", "Priya", "Neha", "Rohan",
        "Karan", "Sneha", "Vivek", "Pooja", "Arjun",
        "Mehul", "Riya", "Jay", "Anjali", "Harsh",
        "Nisha", "Dhruv", "Kavya", "Yash", "Isha"
    ],

    "Number": [
        9876543210, 9876543211, 9876543212, None, 9876543214,
        9876543215, 9876543216, None, 9876543218, 9876543219,
        9876543220, 9876543221, None, 9876543223, 9876543224,
        9876543225, 9876543226, None, 9876543228, 9876543229
    ],

    "City": [
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", None,
        "Ahmedabad", "Surat", "Mumbai", "Pune", None,
        "Delhi", "Ahmedabad", "Rajkot", "Surat", None,
        "Vadodara", "Mumbai", "Pune", "Ahmedabad", "Delhi"
    ],

    "Salary": [
        35000, 42000, None, 38000, 50000,
        45000, None, 60000, 32000, 55000,
        48000, None, 40000, 37000, 52000,
        46000, None, 58000, 41000, 65000
    ],

    "Age": [
        23, 25, None, 28, 31,
        26, 24, None, 22, 30,
        27, 29, 25, None, 32,
        28, 26, 34, None, 35
    ],

    "Total": [
        70000, 84000, 65000, None, 100000,
        90000, 72000, 120000, None, 110000,
        96000, 78000, None, 74000, 104000,
        92000, 88000, None, 82000, 130000
    ]
}

df = pd.DataFrame(data)

print(df)

      Name        Number       City   Salary   Age     Total
0    Rahul  9.876543e+09  Ahmedabad  35000.0  23.0   70000.0
1     Amit  9.876543e+09      Surat  42000.0  25.0   84000.0
2    Priya  9.876543e+09   Vadodara      NaN   NaN   65000.0
3     Neha           NaN     Rajkot  38000.0  28.0       NaN
4    Rohan  9.876543e+09        NaN  50000.0  31.0  100000.0
5    Karan  9.876543e+09  Ahmedabad  45000.0  26.0   90000.0
6    Sneha  9.876543e+09      Surat      NaN  24.0   72000.0
7    Vivek           NaN     Mumbai  60000.0   NaN  120000.0
8    Pooja  9.876543e+09       Pune  32000.0  22.0       NaN
9    Arjun  9.876543e+09        NaN  55000.0  30.0  110000.0
10   Mehul  9.876543e+09      Delhi  48000.0  27.0   96000.0
11    Riya  9.876543e+09  Ahmedabad      NaN  29.0   78000.0
12     Jay           NaN     Rajkot  40000.0  25.0       NaN
13  Anjali  9.876543e+09      Surat  37000.0   NaN   74000.0
14   Harsh  9.876543e+09        NaN  52000.0  32.0  104000.0
15   Nisha  9.876543e+09   Vadodara  46000.0  28.0   92000.0
16   Dhruv  9.876543e+09     Mumbai      NaN  26.0   88000.0
17   Kavya           NaN       Pune  58000.0  34.0       NaN
18    Yash  9.876543e+09  Ahmedabad  41000.0   NaN   82000.0
19    Isha  9.876543e+09      Delhi  65000.0  35.0  130000.0

In [45]:
df.isnull().sum()

Name      0
Number    4
City      3
Salary    4
Age       4
Total     4
dtype: int64

In [46]:
df.isna().sum()

Name      0
Number    4
City      3
Salary    4
Age       4
Total     4
dtype: int64

In [47]:
df.notnull().sum()

Name      20
Number    16
City      17
Salary    16
Age       16
Total     16
dtype: int64

In [48]:
df.dropna(axis=1)

      Name
0    Rahul
1     Amit
2    Priya
3     Neha
4    Rohan
5    Karan
6    Sneha
7    Vivek
8    Pooja
9    Arjun
10   Mehul
11    Riya
12     Jay
13  Anjali
14   Harsh
15   Nisha
16   Dhruv
17   Kavya
18    Yash
19    Isha

In [49]:
df.dropna(thresh=4)

      Name        Number       City   Salary   Age     Total
0    Rahul  9.876543e+09  Ahmedabad  35000.0  23.0   70000.0
1     Amit  9.876543e+09      Surat  42000.0  25.0   84000.0
2    Priya  9.876543e+09   Vadodara      NaN   NaN   65000.0
3     Neha           NaN     Rajkot  38000.0  28.0       NaN
4    Rohan  9.876543e+09        NaN  50000.0  31.0  100000.0
5    Karan  9.876543e+09  Ahmedabad  45000.0  26.0   90000.0
6    Sneha  9.876543e+09      Surat      NaN  24.0   72000.0
7    Vivek           NaN     Mumbai  60000.0   NaN  120000.0
8    Pooja  9.876543e+09       Pune  32000.0  22.0       NaN
9    Arjun  9.876543e+09        NaN  55000.0  30.0  110000.0
10   Mehul  9.876543e+09      Delhi  48000.0  27.0   96000.0
11    Riya  9.876543e+09  Ahmedabad      NaN  29.0   78000.0
12     Jay           NaN     Rajkot  40000.0  25.0       NaN
13  Anjali  9.876543e+09      Surat  37000.0   NaN   74000.0
14   Harsh  9.876543e+09        NaN  52000.0  32.0  104000.0
15   Nisha  9.876543e+09   Vadodara  46000.0  28.0   92000.0
16   Dhruv  9.876543e+09     Mumbai      NaN  26.0   88000.0
17   Kavya           NaN       Pune  58000.0  34.0       NaN
18    Yash  9.876543e+09  Ahmedabad  41000.0   NaN   82000.0
19    Isha  9.876543e+09      Delhi  65000.0  35.0  130000.0

In [50]:
# df["Age"].fillna(69)

# mean = df["Age"].mean()
# df["Age"].fillna(mean)

In [51]:
# df["Age"].bfill()

In [52]:
df["Age"].ffill()

0     23.0
1     25.0
2     25.0
3     28.0
4     31.0
5     26.0
6     24.0
7     24.0
8     22.0
9     30.0
10    27.0
11    29.0
12    25.0
13    25.0
14    32.0
15    28.0
16    26.0
17    34.0
18    34.0
19    35.0
Name: Age, dtype: float64